# 使用 .NET 6 SDK 作為基礎映像
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# 複製專案文件並還原依賴項
COPY *.sln .
COPY REST/*.csproj ./REST/
RUN dotnet restore

# 複製其餘的應用程式文件並進行編譯
COPY REST/. ./REST/
WORKDIR /app/REST
RUN dotnet publish -c Release -o out

# 使用 .NET 6 Runtime 作為基礎映像
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/REST/out ./

# 暴露應用程式的埠
EXPOSE 5099
EXPOSE 7068

# 啟動應用程式
ENTRYPOINT ["dotnet", "REST.dll"]